apiVersion: v1
kind: ServiceAccount
metadata:
  name: "impersonate-helm-broker"
  namespace: "impersonate-helm-broker"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: impersonator
rules:
  - apiGroups: [""]
    resources: ["users", "groups", "serviceaccounts"]
    verbs: ["impersonate"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: "impersonate-helm-broker-impersonator"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: impersonator
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: "impersonate-helm-broker"
    namespace: "impersonate-helm-broker"
